blank_issues_enabled: false
contact_links:
  - name: ConfigCar and ProTagged Developer Community Discussions
    url: https://github.com/protagged/tbd/discussions
    about: Please ask and answer questions here.
