# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Persona
description: Add a new persona to the application, system or service requirements
title: "[PERSONA]: "
labels: ["PERSONA"]
body:
  - type: markdown
    attributes:
      value: |
        A **persona** is an archetypical user of a system, an example of the
        kind of person who would interact with the system to be designed.

  - type: textarea
    id: persona-bio
    attributes:
      label: "Biography"
      description: "Please describe the **persona** in a short, personal bio form."
      placeholder: >
        Example: Warin is a ground handling agent at Lufthansa, passionate
        about safe operation and delivering for  Lufthansa customers. He takes
        pride on his ability to solve problems, always looking for innovative solutions
        that can lead to an improvement for the customer, supported by his colleagues
        where required. He is proactive and happy working on his own or in
        managing a team. He also enjoy being outdoors whatever the weather is and
        keeping himself fit enabling to comfortably do manual handling activities.
    validations:
      required: true

  - type: dropdown
    id: persona-gender
    attributes:
      label: "Gender"
      description: >
        Gender identity is the personal sense of one's own gender. Gender includes the
        social, psychological, cultural and behavioral aspects of being a man, woman,
        or other gender identity.
      options:
        - male
        - female
        - diverse

  - type: dropdown
    id: persona-generation
    attributes:
      label: "Generation"
      description: >
        Social generations are cohorts of people born in the same date range and who share
        similar cultural experiences.
        See [here](https://www.beresfordresearch.com/age-range-by-generation/) for more background.
      options:
        - Gen Z	(born 1997-2012)
        - Millennials	(born 1981-1996)
        - Gen X	(born 1965-1980)
        - Boomers II (born 1955-1964)
        - Boomers I	(born 1946-1954)
        - Post War (born 1928-1945)
        - WWII (born 1922-1927)

  - type: dropdown
    id: persona-archetype
    attributes:
      label: "Archetype"
      description: >
        Every good story is made up of interesting characters. In narrative theory, there are 12 classic archetypes.
        They each play a specific role and have goals, motivations, strengths, weaknesses, and complementary characters.
        See [here](https://www.method.com/insights/how-to-use-personas-and-archetypes-to-drive-shared-understanding-and-digital-strategy/) for more background.
      options:
        - The Innocent
        - The Everyman/woman
        - The Hero
        - The Caregiver
        - The Explorer
        - The Rebel
        - The Lover
        - The Creator
        - The Jester
        - The Sage
        - The Magician
        - The Ruler

  - type: textarea
    id: persona-goals
    attributes:
      label: "Goals"
      description: "What are the (typical or primary) goals of the *Persona*?"
      placeholder: >
        Example:
        - Take pride in getting a job done right
        - Identify continuous improvement opportunities, learning from causes of issues
          and delays
        - Role model behavior providing shadowing support and mentoring colleagues as
          required
    validations:
      required: true

